title: QMIO OpenPulse Tutorials
author: Alfredo Chavert Sancho
execute:
  execute_notebooks: "off"

# AÃ±ade esto para evitar que JB intente leer carpetas del sistema o de la propia build
exclude_patterns: ["_build", "Thumbs.db", ".DS_Store", ".git", ".github", "venv", ".ipynb_checkpoints"]
