title: QMIO OpenPulse Course
author: "Alfredo Chavert Sancho"

execute:
  execute_notebooks: off
  
repository:
  url: https://github.com/achavert/qmio-openpulse
  branch: main
html:
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
