title: QMIO OpenPulse Tutorials
author: Alfredo Chavert Sancho
execute:
  execute_notebooks: "off"

# Esto es lo m√°s importante para evitar el error EISDIR
exclude_patterns: 
  - "_build"
  - ".git"
  - ".github"
  - "**.ipynb_checkpoints"
  - ".DS_Store"
  - "Thumbs.db"
  - "venv"
